POST http://localhost:4030/auth/register
Content-Type: application/json

{
    "name": "testparams" ,
    "email": "params@gmail.com" ,
    "password": "mamae123"
}

###

POST http://localhost:4030/auth/authenticate
Content-Type: application/json

{
    "email": "params@gmail.com" ,
    "password": "mamae123"
}

###

GET http://localhost:4030/projects
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTk0Nzk3MDcsImV4cCI6MTY1OTU2NjEwN30.trYofp_rtQuegp7uDffVDJgxDrj9vqyo0XExAQlpKLY






