POST http://localhost:4030/produtos
Content-Type: application/json

{
    "name": "Bala doce" ,
    "price": 0.1
}

###

GET http://localhost:4030/produtos

###

GET http://localhost:4030/produtos/ccc3cf68-15e8-4fb8-8073-f2903af83f2d
###

PUT http://localhost:4030/produtos/ccc3cf68-15e8-4fb8-8073-f2903af83f2d
Content-Type: application/json

{
    "name": "Bala Salgada" ,
    "price": 0.1
}

###

DELETE http://localhost:4030/produtos/c650a779-384d-43e5-9a66-4278b1bcd6e2